name: OnePlus 13R
on:
  workflow_dispatch:
    inputs:
      CPU:
        type: choice
        description: "Platform"
        required: true
        default: 'sm8650'
        options: 
         - sm8750
         - sm8650
      FEIL:
        type: choice
        description: "Model"
        required: true
        default: 'oneplus_13r'
        options: 
         - oneplus_13
         - oneplus_13_v
         - oneplus_13t
         - oneplus_ace5_pro
         - oneplus_ace5_pro_v
         - oneplus_ace5
         - oneplus_13r
      CPUD:
        type: choice
        description: "Phone Code"
        required: true
        default: 'pineapple'
        options: 
         - sun
         - pineapple
      ANDROID_VERSION:
        type: choice
        description: "Operating System"
        required: true
        default: 'android14'
        options: 
         - android15
         - android14
      KERNEL_VERSION:
        type: choice
        description: "Kernel Version"
        required: true
        default: '6.1'
        options: 
         - '6.6'
         - '6.1'
      KERNEL_NAME:
        description: "Kernel Name"
        required: true
        default: '-android14-11-o-g7cddc8f99e91'
      KERNEL_TIME:
       description: "Kernel Build Date"
       required: true
       default: 'Wed Dec 4 02:11:46 UTC 2024'
      enable_feature_x:
       description: "Enable KPM"
       required: false
       default: true
       type: boolean
      enable_feature_z:
       description: "Enable Fengchi"
       required: false
       default: true
       type: boolean
      ANYKERNEL_BRANCH:
       description: "AnyKernel3 Branch"
       required: true
       default: 'gki-2.0'

jobs:
  OnePlus-Kernel-Build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    
    steps:
      - name: Set formatted model name
        run: |
         case "${{ github.event.inputs.FEIL }}" in
           oneplus_13)
            MODEL_NAME="Oneplus 13"
            ;;
           oneplus_13_v)
            MODEL_NAME="Oneplus 13 (Android 15)"
            ;;
          oneplus_13t)
             MODEL_NAME="Oneplus 13T"
            ;;
           oneplus_ace5)
             MODEL_NAME="Oneplus Ace 5"
            ;;
           oneplus_13r)
             MODEL_NAME="Oneplus 13R"
            ;;
           oneplus_ace5_pro)
            MODEL_NAME="Oneplus Ace 5 Pro"
            ;;
           oneplus_ace5_pro_v)
            MODEL_NAME="Oneplus Ace 5 Pro (Android 15)"
            ;;
           *)
            MODEL_NAME="Unknown Model"
            ;;
         esac
         echo "FEIL_NAME=$MODEL_NAME" >> "$GITHUB_ENV"
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: Configure Git
        run: |
         git config --global user.name "O+builder"
         git config --global user.email "O+builder@yahoo.com"

      - name: Install dependencies
        run: |
         sudo apt update && sudo apt upgrade -y
         sudo apt install -y python3 git curl libelf-dev lld

      - name: Install repo tool
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
         mkdir kernel_workspace && cd kernel_workspace
         repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ inputs.CPU }} -m ${{ inputs.FEIL }}.xml --depth=1
         repo --trace sync -c -j$(nproc --all) --no-tags
         rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
         rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
         
      - name: Set up SukiSU
        run: |
         cd kernel_workspace/kernel_platform
         curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
         cd ./KernelSU
         KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10606)
         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
         export KSU_VERSION=$KSU_VERSION
         sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
        
      - name: Set up susfs
        run: |
           cd kernel_workspace
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}
           git clone https://github.com/ShirkNeko/SukiSU_patch.git

           cd kernel_platform
           cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}.patch ./common/
           cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
           
           # Apply patches
           cd ./common
           
           MODEL="${{ inputs.FEIL }}"
           if [[ "$MODEL" =~ oneplus_13 || "$MODEL" =~ ace5_pro ]] && [[ "$MODEL" != "oneplus_13t" ]]; then
             FILENAME="50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}.patch"
             sed -i 's/-32,12 +32,38/-32,11 +32,37/g' "$FILENAME"
             sed -i '/#include <trace\/hooks\/fs.h>/d' "$FILENAME"
           fi

           patch -p1 < 50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}.patch || true
           cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
           patch -p1 -F 3 < syscall_hooks.patch
           echo "Completed"

      - name: Apply HMBird GKI patch
        if: contains( inputs.FEIL, 'ace5_pro' )
        run: |
         cd kernel_workspace/kernel_platform/common/drivers
         cat << 'EOF' > hmbird_patch.c
         #include <linux/init.h>
         #include <linux/module.h>
         #include <linux/of.h>
         #include <linux/slab.h>
         #include <linux/string.h>

         static int __init hmbird_patch_init(void)
         {
             struct device_node *ver_np;
             const char *type;
             int ret;

             ver_np = of_find_node_by_path("/soc/oplus,hmbird/version_type");
             if (!ver_np) {
                  pr_info("hmbird_patch: version_type node not found\n");
                  return 0;
             }

             ret = of_property_read_string(ver_np, "type", &type);
             if (ret) {
                  pr_info("hmbird_patch: type property not found\n");
                  of_node_put(ver_np);
                  return 0;
             }

             if (strcmp(type, "HMBIRD_OGKI")) {
                  of_node_put(ver_np);
                  return 0;
             }

             struct property *prop = of_find_property(ver_np, "type", NULL);
             if (prop) {
                  struct property *new_prop = kmalloc(sizeof(*prop), GFP_KERNEL);
                  if (!new_prop) {
                       pr_info("hmbird_patch: kmalloc for new_prop failed\n");
                       of_node_put(ver_np);
                       return 0;
             }
             memcpy(new_prop, prop, sizeof(*prop));
             new_prop->value = kmalloc(strlen("HMBIRD_GKI") + 1, GFP_KERNEL);
             if (!new_prop->value) {
                  pr_info("hmbird_patch: kmalloc for new_prop->value failed\n");
                  kfree(new_prop);
                  of_node_put(ver_np);
                  return 0;
            }
            strcpy(new_prop->value, "HMBIRD_GKI");
            new_prop->length = strlen("HMBIRD_GKI") + 1;

            if (of_remove_property(ver_np, prop) != 0) {
                 pr_info("hmbird_patch: of_remove_property failed\n");
                 return 0;
            }
            if (of_add_property(ver_np, new_prop) !=0) {
                 pr_info("hmbird_patch: of_add_property failed\n");
                 return 0;
            }
            pr_info("hmbird_patch: success from HMBIRD_OGKI to HMBIRD_GKI\n");
         }
         else {
             pr_info("hmbird_patch: type property structure not found\n");
         }
         of_node_put(ver_np);
         return 0;
         }
         early_initcall(hmbird_patch_init);
         MODULE_LICENSE("GPL");
         MODULE_AUTHOR("reigadegr");
         MODULE_DESCRIPTION("Forcefully convert HMBIRD_OGKI to HMBIRD_GKI.");
         EOF
         if ! grep -q "hmbird_patch.o" Makefile; then
         echo "obj-y += hmbird_patch.o" >> Makefile
         fi
         cd ../../../
         git add -A
         git commit -m "Add HMBird GKI patch" || true

      - name: Add SUSFS Configuration Settings
        run: |
          cd kernel_workspace/kernel_platform
          # Add KSU configuration settings
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_KPROBES_HOOK=n" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Add SUSFS configuration settings
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Add additional tmpfs config setting
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Remove check_defconfig
          sudo sed -i 's/check_defconfig//' ./common/build.config.gki
          cd common
          git add -A && git commit -a -m "BUILD Kernel"
      
      - name: Add BBR Support
        run: |
          cd kernel_workspace/kernel_platform
          
          echo "Adding configuration settings to gki_defconfig..."
          echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_BIC=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_HTCP=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_NET_SCH_FQ=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_NET_SCH_FQ_CODEL=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IPV6_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_NF_TARGET_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_DEBUG_KERNEL=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_DYNAMIC_DEBUG=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_DEBUG_INFO=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_BOEFFLA_WL_BLOCKER=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_WQ_POWER_EFFICIENT_DEFAULT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          cd common
          git add -A && git commit -a -m "Add BBR Support"

      - name: Add TTL Target Support
        run: |
          cd kernel_workspace/kernel_platform
          
          echo "Adding configuration settings to gki_defconfig..."
          for config in \
              "CONFIG_IP_NF_TARGET_TTL=y" \
              "CONFIG_IP6_NF_TARGET_HL=y" \
              "CONFIG_IP6_NF_MATCH_HL=y" \
              "CONFIG_EXT4_INODE_TEST=n" \
              "CONFIG_F_FS_IPC_LOG=n" \
              "CONFIG_HUNG_TASK_ENH=n" \
              "CONFIG_IIO_TEST_FORMAT=n" \
              "CONFIG_OPLUS_BSP_SIGKILL_DIAGNOSIS=n" \
              "CONFIG_OPLUS_LOCK_TORTURE=n" \
              "CONFIG_SOC_TOPOLOGY_TEST=n" \
              "CONFIG_SOC_UTILS_TEST=n" \
              "CONFIG_DEBUG_KERNEL=n" \
              "CONFIG_DYNAMIC_DEBUG=n" \
              "CONFIG_DEBUG_INFO=n"; do
              echo "$config" >> ./common/arch/arm64/configs/gki_defconfig
          done
          
          cd common
          git add -A && git commit -a -m "Add TTL Target Support"
          
      - name: Add KPM Configuration Settings
        if: ${{ inputs.enable_feature_x }}
        run: |
          cd kernel_workspace/kernel_platform
          echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
          sudo sed -i 's/check_defconfig//' ./common/build.config.gki
          cd common
          git add -A && git commit -a -m "BUILD Kernel"
          
      - name: Add Fengchi
        if: ${{ inputs.enable_feature_z }}
        run: |
         cd kernel_workspace/kernel_platform/
         git clone https://github.com/HanKuCha/sched_ext.git
         cp -r ./sched_ext/* ./common/kernel/sched
         rm -rf ./sched_ext/.git
         cd common/kernel/sched

      - name: Set Kernel build timestamp
        run: |
          export SOURCE_DATE_EPOCH=$(date -d "${{ inputs.KERNEL_TIME }}" +%s)
          echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV
          echo "BUILDDATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          
      - name: Build Kernel
        run: |
           export SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
           cd kernel_workspace/kernel_platform
           tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist
           
      - name: Apply Linux Patch
        run: |
         MODEL="${{ inputs.FEIL }}"
         cd kernel_workspace/kernel_platform/dist/
         curl -LO https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/latest/download/patch_linux
         chmod +x patch_linux
         ./patch_linux
         rm -f Image
         mv oImage Image
         
      - name: Clone AnyKernel3 and Other Dependencies
        env:
          IMG_FILE: "${{ inputs.FEIL }}_Image_SukiSU_Ultra_${{ env.KSUVER }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}-${{ env.BUILDDATE }}"
          ANYKERNEL3_FILE: "${{ inputs.FEIL }}_SukiSU_Ultra_${{ env.KSUVER }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}-${{ env.BUILDDATE }}"
        run: |
          echo "Cloning AnyKernel3 and other dependencies..."
          
          ANYKERNEL_BRANCH="${{ inputs.ANYKERNEL_BRANCH }}"
          
          # Debug print the branch
          echo "Using branch for AnyKernel3: $ANYKERNEL_BRANCH"
          
          # Clone repositories using the branch names
          git clone https://github.com/TheWildJames/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
          git clone https://github.com/TheWildJames/kernel_patches.git
          
          # Copy kernel image to AnyKernel3
          cp kernel_workspace/kernel_platform/dist/Image ./AnyKernel3/
          
          # Modify anykernel.sh for specific models
          cd ./AnyKernel3
          if [[ "${{ inputs.FEIL }}" == "oneplus_13" || "${{ inputs.FEIL }}" == "oneplus_ace5_pro" ]]; then
            sed -i '/flash_boot/a flash_dtbo' ./anykernel.sh
          fi

      - name: Upload AnyKernel3
        env:
          ANYKERNEL3_FILE: "${{ inputs.FEIL }}_SukiSU_Ultra_${{ env.KSUVER }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}-${{ env.BUILDDATE }}"
        uses: actions/upload-artifact@v4
        with:
         name: ${{ env.ANYKERNEL3_FILE }}
         path: ./AnyKernel3/*
        
      - name: Upload Image
        env:
          IMG_FILE: "${{ inputs.FEIL }}_Image_SukiSU_Ultra_${{ env.KSUVER }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}-${{ env.BUILDDATE }}"
        uses: actions/upload-artifact@v4
        with:
         name: ${{ env.IMG_FILE }}
         path: kernel_workspace/kernel_platform/dist/Image

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: download

      - name: Create ZIP Files for Different Formats
        env:
          IMG_FILE: "${{ inputs.FEIL }}_Image_SukiSU_Ultra_${{ env.KSUVER }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}-${{ env.BUILDDATE }}"
          ANYKERNEL3_FILE: "${{ inputs.FEIL }}_SukiSU_Ultra_${{ env.KSUVER }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}-${{ env.BUILDDATE }}"
        run: |
          echo "Navigating to AnyKernel3 directory..."
          cd ./AnyKernel3
          
          # Zip the files in the AnyKernel3 directory with a new naming convention
          ZIP_NAME="${{ inputs.FEIL }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}_Next_SUSFS_AnyKernel3.zip"
          echo "Creating zip file $ZIP_NAME..."
          zip -r "../$ZIP_NAME" ./*
          
          echo "Navigating to Image directory..."
          cd ../download/${{ env.IMG_FILE }}
          IMAGE_ZIP_NAME="${{ inputs.FEIL }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}_Next_SUSFS_Image.zip"
          echo "Creating zip file $IMAGE_ZIP_NAME..."
          zip -r "../../$IMAGE_ZIP_NAME" ./*
          
          echo "Copying boot.img..."
          cp ../kernel_workspace/kernel_platform/dist/boot.img ../${{ inputs.FEIL }}_boot.img

      - name: Create GitHub Release
        env:
          IMG_FILE: "${{ inputs.FEIL }}_Image_SukiSU_Ultra_${{ env.KSUVER }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}-${{ env.BUILDDATE }}"
          ANYKERNEL3_FILE: "${{ inputs.FEIL }}_SukiSU_Ultra_${{ env.KSUVER }}_${{ inputs.ANDROID_VERSION }}_${{ inputs.KERNEL_VERSION }}-${{ env.BUILDDATE }}"
          RELEASE_NAME: "${{env.FEIL_NAME}} Kernel - GKI/SukiSU Ultra/SUSFS"
          RELEASE_NOTES: |                     
           
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.FEIL }}-SukiSU_Ultra-v${{ env.BUILDDATE }}.${{ github.run_number }}
          files: |
            ./*.zip
            ./*.img
          generate_release_notes: true
          name: ${{ env.RELEASE_NAME }}
          body: ${{ env.RELEASE_NOTES }}
